# Generated by Django 3.1.1 on 2020-10-08 06:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lighttown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='builder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='session',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='town',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='date_finished',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='date_started',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_completed',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='town_name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
