# Generated by Django 3.1.2 on 2020-10-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Town', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='thumbnail',
            field=models.ImageField(default='town.jpg', upload_to='town/town/%Y/%m/%d'),
        ),
    ]
