# Generated by Django 3.1.1 on 2020-10-08 06:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Town', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=140)),
                ('date_started', models.DateTimeField(blank=True)),
                ('date_finished', models.DateTimeField(blank=True)),
                ('session', models.DurationField(default=datetime.timedelta(days=1))),
                ('is_completed', models.BooleanField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Town.town')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=300)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.house')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
