# Generated by Django 3.1.2 on 2020-10-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='town_name',
            field=models.JSONField(null=True),
        ),
    ]
